name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: "120s"
        script: |
          cd fastapi-book-project-1 || exit 1
          git pull origin main
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          if ! command -v pip &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y python3-pip
          fi
          pip install -r requirements.txt
          sudo systemctl restart fastapi || echo "fastapi service not found"
          sudo systemctl restart nginx || echo "nginx service not found"